### ISSUE TITLE
EVCC Support

### ISSUE THREAD

**Issue by bigbenFE** [dgthomson/nodered-shellrecharge#10]
Hi,

so that the Shell NewMotion wallboxes can be supported in EVCC, andig would need the info which requests end in which format on which endpoint. could you help me and other Shell NewMotion users who would like to use EVCC? He would need at least the values ​​for start, stop, vehicle connected. If you could adjust the amperage to adapt the wallbox to the PV system, that would be even better :)
It requires data similar to the shell documentation: https://developer.shell.com/api-catalog/b2b-ev-charge-sessions/quick-start-guide

Thank you very much and greetings from Berlin =)

**Comment by dgthomson** [comment]
Shell Recharge will not allow home users to access their API. This subflow simulates a login to the Shell Recharge website only so doesn't use the API directly. An EVCC developer is welcome to adapt this code to work in the app.

**Comment by bigbenFE** [comment]
OK, but how can andig query the data from EVCC? he would need the info which requests end in which format on which endpoint. he has neither the time nor the inclination to reverse engineer it.

**Comment by bigbenFE** [comment]
> Shell Recharge will not allow home users to access their API. This subflow simulates a login to the Shell Recharge website only so doesn't use the API directly. An EVCC developer is welcome to adapt this code to work in the app.

OK, but how can andig query the data from EVCC? he would need the info which requests end in which format on which endpoint. he has neither the time nor the inclination to reverse engineer it.
