### ISSUE TITLE
Account without charge point, only a card

### ISSUE THREAD

**Issue by Tiebe** [dgthomson/nodered-shellrecharge#11]
I have a NewMotion account that isn't linked to a charge point. I only have a charge card. Is it still possible to use this node?

**Comment by dgthomson** [comment]
i doubt it. the flow fakes an interaction with the account.shellrecharge.com website, so if you can see linked charge points and charge cards displayed there's a good chance you can control them.

**Comment by dgthomson** [comment]
Closed.
