### ISSUE TITLE
HTTP Error [ETIMEDOUT:start]

### ISSUE THREAD

**Issue by madradrakie** [dgthomson/nodered-shellrecharge#12]
Hello,

Any idea what is going wrong? Most of the time when i want to start a charging session i get the following error: HTTP Error [ETIMEDOUT:start].

I hope someone can help me,

Greetings.

**Comment by dgthomson** [comment]
you could try this...

in the shell recharge node, click 'edit subflow template'
look for a section marked 'ƒ HTTP [2023-04-23]'
open the second node labelled 'Cache'
click '+ add'
into the boxes, enter
 [Set] msg.requestTimeout
 to the value [0-9] 10000
Done, then Deploy.
 
that error means that the subflow has given up waiting for shell to answer a request. this fix makes it wait longer.

**Comment by madradrakie** [comment]
Thanks for your replay. I only see 'ƒ HTTP [2023-04-09]'. I imported the sr-2-19.json

![image](https://github.com/dgthomson/nodered-shellrecharge/assets/55043830/2d1445b7-5599-43a4-ac0e-c23faddea2f4)

**Comment by dgthomson** [comment]
Sorry, I have probably changed that section without sharing it on my nodered. You can achieve the same result by putting a ‘change’ node between the first two nodes (grey right arrow and globe) containing…

[Set] msg.requestTimeout
to the value [0-9] 10000

**Comment by madradrakie** [comment]
thanks, it is working again :-)
