### ISSUE TITLE
Charging status not updating

### ISSUE THREAD

**Issue by Marc1200** [dgthomson/nodered-shellrecharge#13]
I have a problem, when i start charging session, i poll a minute if the charger is charging but that isn't working.
It says status unknown
I did a token expire but that did not help.

Whats problem here
 when i poll once is says poll payload: occupied.

**Comment by dgthomson** [comment]
I can't replicate this, sorry. The same code runs for both scenarios. But I have found an error in the documentation. Make sure that your polling payload is right:

`msg.payload = { "action": "rpoll", "poll": {"interval": 5, "duration": 20 } }`

**Comment by Marc1200** [comment]
yes polling does work for me, it only polls the idle state. i get no charging status anymore

**Comment by dgthomson** [comment]
i have a theory. do you have more than 1 charger? please send the output from

`msg.payload = {"action":"setup"}`

**Comment by Marc1200** [comment]
We have one charger and two different charging accounts.
I will send the output later this day 

I do not have the newest release running, maybe thats the problem, i just saw, you updated the repository last week.

**Comment by Marc1200** [comment]
![image](https://github.com/dgthomson/nodered-shellrecharge/assets/68737063/51e57265-c8cf-4f57-b06c-54ea69f67d0b)

**Comment by Marc1200** [comment]
should i maybe update to sr-2-20.json from sr-2-19.json?

**Comment by Marc1200** [comment]
Charging update still not working with the newest version.
![image](https://github.com/dgthomson/nodered-shellrecharge/assets/68737063/81cfad35-9ef6-4a7e-889f-83cc4b4415e1)
![image](https://github.com/dgthomson/nodered-shellrecharge/assets/68737063/699d990f-6548-4b67-9b95-639157f697f4)
