### ISSUE TITLE
Poll not working

### ISSUE THREAD

**Issue by yoannHertienne** [dgthomson/nodered-shellrecharge#14]
Hello,

I updated the subflow using sr-2-20.json and now i'm getting the following error on Poll Once: {"action":"poll"}

"TypeError: Cannot read properties of undefined (reading 'evses')"

**Comment by dgthomson** [comment]
something's changing at their end and i'm not sure what it is, but i have a theory.

can you send the full debug output from `msg.payload = {"action":"setup"}`

if you're up for fiddling, can you open up the subflow and look for the section 'ƒ POLL [2023-04-15]'. the first function node there, there's a line in the code...

`msg.payload = msg.payload.chargePoints[msg.shellrecharge.cid].evses[0].status;`

try changing the number in square brackets '...evses[1]...' etc

**Comment by yoannHertienne** [comment]
@dgthomson : please find the debug output for {"action":"setup"}:
<img width="288" alt="image" src="https://github.com/dgthomson/nodered-shellrecharge/assets/18640533/d803b202-d07a-495a-a92d-656a1f1b41ae">

FYI: I remove the RFID, because my physical card was not working. New one has been ordered, maybe it can be the cause.

**Comment by yoannHertienne** [comment]
@dgthomson I found the issue. When I change `msg.payload = msg.payload.chargePoints[msg.shellrecharge.cid].evses[0].status;` to `msg.payload = msg.payload.chargePoints[0].evses[0].status;` it's working, so not sure what is the value of `msg.shellrecharge.cid`

**Comment by dgthomson** [comment]
`msg.shellrecharge.cid` is set from the subflow properties as 'Charger ID'...

 ![subflow properties](https://user-images.githubusercontent.com/2021563/221416402-dcf6de7b-a260-4730-b201-865174e37598.png)

If you have 'Charger ID' as 0 then that'd be the same as `msg.payload = msg.payload.chargePoints[0].evses[0].status`

**Comment by yoannHertienne** [comment]
Ok my bad, I was still using the full object instead of the ID 0.
