### ISSUE TITLE
Can i use two or more ChargeCards?

### ISSUE THREAD

**Issue by bigbenFE** [dgthomson/nodered-shellrecharge#16]
Hello,
I have two private charging cards and one of the work, the work card should be assigned to the company car without photovoltaics in EVCC and private charging cards to the private MG4 and photovoltaic.
I have set the official card as the standard in Shell's account, but the nodered-shellrecharge always starts loading with the private account. can i the nodered-shellrecharge say which card it should use?
In addition, the nodered-shellrecharge cannot identify the cars? so EVCC cannot assign the cars :(

`{"_msgid":"7a8f3c7aa51c5cae","payload":{"chargeTokens":[{"name":"Ben Privat","printedNumber":"DE-TNM-***-*","rfid":"04B1CD***","uuid":"a04d226a-***"},{"name":"Ben Arbeit","printedNumber":"DE***","rfid":"544***","uuid":"487e70ea-***"},{"name":"Maria Privat","printedNumber":"DE-TNM-***","rfid":"044***","uuid":"d2d3e409-***"}],"chargePoints":[{"evses":[{"evseId":"DE*TNM*E****0","number":0,"occupyingToken":{"printedNumber":"DE-TNM-***","rfid":"04B1***","timestamp":"2023-08-04T08:28:30.000Z"},"status":"Charging"}],"name":"Lade***","serial":"***","uuid":"bc7b00e0-***"}],"identity":{"country":"Germany","countryCode":"de","email":"***@***","externalId":"0012X0***","firstName":"Benjamin","id":"9a22a09e-***","isSuperUser":false,"lastName":"***","locale":"de_DE","status":"active"}},"_event":"node:1557d6a2474bc320"}`

**Comment by dgthomson** [comment]
<img width="507" alt="Screenshot 2023-08-08 at 22 08 58" src="https://github.com/dgthomson/nodered-shellrecharge/assets/2021563/376b6e6a-bef3-4aa1-9d91-1f005f5f40a1">

In 'Card ID' in the Edit Subflow Instance section of the Shell Recharge node, typing '0' should use charge card 'Ben Privat', '1' will use 'Ben Arbeit' and '2' will use 'Maria Privat'.

You can also send a payload to the node directly like: 
```
msg.payload = {
   "action":"start",
   "cid":"0",
   "tid":"1"
}
```
This would start a charge using your only charger and card 'Ben Arbeit' .

**Comment by bigbenFE** [comment]
That's great, thank you very much. Do you know how I can do the following in the Rednode: If EVCC enable = true sends, it must first be checked which of the two vehicles is connected and then send the right command, so far it looks like this:

`NodeRed "MQTTin" : shell/enable, than "change" msg.payload : true change to "{"action":"start","delay":false,"_comment":"delay_optional"}" or msg.payload : false change to "{"action":"stop"}" to the Shell Recharge NodeRed `  

The MG4 can also be called up via MQTT, so that it would be enough to recognize whether it is connected.
So that the private card is used for connected MG4 and if not the official?

![grafik](https://github.com/dgthomson/nodered-shellrecharge/assets/76753841/33e47189-ff3b-4e6f-b0da-8ba916810435)


Sorry for Google Translate, German would be easier;)
