### ISSUE TITLE
Status keeps stating "charging" after charging is done, but still plugged in

### ISSUE THREAD

**Issue by hjnijlunsing** [dgthomson/nodered-shellrecharge#18]
I noticed that the status only changed from "charging" to "available" after physically disconnecting the cable.
I guess this is probably something on the Shell side which can't be fixed.

Not a deal breaker for me though as I am able to monitor the battery SOC with an ODB plug and can use that to detect if the charging has finished.

**Comment by dgthomson** [comment]
The status comes directly from Shell and is the same text that's on their website. I think what's shown depends on the charger and the car itself-- mine is plugged in but not charging at the moment but gives 'Available'. I get 'Occupied' if I have started a charge with Shell but the car hasn't started drawing power.
