### ISSUE TITLE
Energy value

### ISSUE THREAD

**Issue by tonsemail** [dgthomson/nodered-shellrecharge#19]
Hi
I set the starttime and the endtime in the EnergyNode to ThisTimeYesterday and ThisTime in the Energy-Node
{"action":"energy","range":{"start":1697572075,"end":1697658475}}

the debug is allways
energy : msg : Object
object
_msgid: "702b9c80d0b7214c"
payload: object
chartTotal: object
totalkWh: "0"
totalkgCO2: "0"
totalTime: 0
totalSessions: 0
chart: array[1]
0: object
date: "20-01-1970"
sessions: 0
kwh: 0
topic: "energy"
_event: "node:c268d9c363297b18-033a44c5214cb9f0"

the date does not change

I do get good values when I inject with the Start-, Stop, or Poll-node. Thes values ocrrespond with the actual state of the charger. How do I get the energy data?

**Comment by dgthomson** [comment]
The start time and end time should be in milliseconds-- the numbers you have used look like seconds.

**Comment by tonsemail** [comment]
THnx, it works now. Perfect! 
Well Almost: Do you know if there is a possibility to get the batterylevel of the connected car.
