### ISSUE TITLE
Chargings status entity is not changing from idle to charging or vice versa 

### ISSUE THREAD

**Issue by Marc1200** [dgthomson/nodered-shellrecharge#20]
The green charging status entity stays on Idle, it don't change to Charging.
It looks like the boolean msg.payload does not change.
`$boolean(msg.payload) = true ? "Charging " & $now('[H#1]:[m01]','+0100') : "Idle " & $now('[H#1]:[m01]','+0100')`

![image](https://github.com/dgthomson/nodered-shellrecharge/assets/68737063/8d34ff46-774e-419e-86c6-5c700dc214b3)

**Comment by dgthomson** [comment]
That code is wrong. Try:

``$boolean($.payload) = true ? "Charging " & $now('[H#1]:[m01]','+0100') : "Idle " & $now('[H#1]:[m01]','+0100')``

**Comment by Marc1200** [comment]
Still not working it stays both in idle mode when charging
It looks like the boolean is not changing in the subflow.

the standard green charging status node is also not changing to charging 

below the settings of the home assistant sensor entity
![image](https://github.com/dgthomson/nodered-shellrecharge/assets/68737063/3eeb1967-5e51-4ead-b617-dfafbc82231b)

**Comment by dgthomson** [comment]
I don't know why this doesn't work for you.

internally, the charging ouput is true if the status is "Charging", otherwise it is false. It's no more complicated than that.

You could use the output of 'poll' in your flow directly with your own nodes to get round this.

**Comment by Marc1200** [comment]
okay i will try

**Comment by Marc1200** [comment]
this is now working after restarting the chargings station
