### ISSUE TITLE
Get HTTP Error 409 when start a charge

### ISSUE THREAD

**Issue by Marc1200** [dgthomson/nodered-shellrecharge#21]
Hello,

Since today i cannot start or stop. It gives an http error 409
What's the problem?
![image](https://github.com/dgthomson/nodered-shellrecharge/assets/68737063/b218bd49-10dc-4d46-a5aa-2a1132757530)

**Comment by dgthomson** [comment]
this is coming from shell.

`The HTTP 409 Conflict response status code indicates a request conflict with the current state of the target resource.`

are you trying to start a charge while it's in the process of stopping or resetting?

**Comment by Marc1200** [comment]
It was indeeds stuck in a charging session, we restarted the charging station and now it works again
