### ISSUE TITLE
TypeError messages as a debug response

### ISSUE THREAD

**Issue by ghost** [dgthomson/nodered-shellrecharge#23]
I configured the node with my user/password and also entered the two uiid's which came back as the response of the setup message ({"action":"setup"}). From my side it looks that the node can login and read successfully all the configured properties from the shell portal (email, name, country,...)

When I press the buttons start, stop, reset or poll one I always get somethink like: 

"TypeError: Cannot read properties of undefined (reading 'evses')"
"TypeError: Cannot read properties of undefined (reading 'uuid')"

At the moment I do not have the additional subscription (Abonnement) ordered, is this required or do you have other ideas what could be the problem?

**Comment by ghost** [comment]
I have the latest version installed

**Comment by dgthomson** [comment]
Check the documentation! Do not enter the `uuid` or `rfid` from the `{"action":"setup"}` process.

`Charger ID` and `Card ID` should be a number, usually `0`.

#
![](https://user-images.githubusercontent.com/2021563/221404599-3fc7cf22-d4d2-4f6d-a7b0-1c2da7774fa2.png)

**Comment by ghost** [comment]
Sorry, I missed that, now it's working, thank you!
