### ISSUE TITLE
Cannot stop Charge

### ISSUE THREAD

**Issue by Edwintenhaaf** [dgthomson/nodered-shellrecharge#24]
Recently starting to have issue when stopping the charge.
<img width="490" alt="image" src="https://github.com/dgthomson/nodered-shellrecharge/assets/51457250/4ddce7c7-d5cc-4b56-b175-da2215f31fb6">
Did not change anything in the payload
<img width="483" alt="image" src="https://github.com/dgthomson/nodered-shellrecharge/assets/51457250/f8acdbe3-6e16-4c10-ac2b-d350e2a5d34f">

Any idea where to look for the cause?
Other flows connecting to internet and local work fine

**Comment by Edwintenhaaf** [comment]
It's fixed by a restart off the Homeassistant VM

**Comment by dgthomson** [comment]
looks like this came from the authentication/login section of the flow. shell would have sent an odd-looking or non-standard login page that the flow couldn't interpret.

**Comment by Edwintenhaaf** [comment]
Yes strange behavior. Flushed cache but only a restart fixed the problem we had for about two weeks.
So now we can charge efficiently again. The car kept charging at most expensive hours because the Stop command did not work.
