### ISSUE TITLE
Intermittent [403:setup] errors as of a few days

### ISSUE THREAD

**Issue by CarloDeSutter** [dgthomson/nodered-shellrecharge#25]
Hi,

Has anyone come across a response body containing [403:setup] when doing the {"action":"setup"} request?
I've seen this only since this week and it seems to go away after at least a few hours.

kr
Carlo

**Comment by CarloDeSutter** [comment]
This morning it worked and then it didn't anymore.
Before this morning, I did make a flush request but this didn't help.

It might be worth knowing that I start and stop sessions, and for each of those actions (start, stop) I perform the following:
- setup
- start/stop
- expire

for security reasons I like to expire the token immediatelly.
This worked fine for over a month.

I also noticed the 403 comes back regardless of the username and password when it does, so seems like either a global issue or some form of throttling (didn't check this last one yet).

Any ideas or experiences ?
kr
Carlo

**Comment by dgthomson** [comment]
OK, I get this too. I'm not at home so haven't spotted this until now. I will have a look.

**Comment by dgthomson** [comment]
Can you test this [new version](https://github.com/dgthomson/nodered-shellrecharge/blob/main/archive/sr-2-50β.json) (2.5) for me?

**Comment by CarloDeSutter** [comment]
Hmm
I replaced the subflow with the 2.5 version, then I get Error! No token. 😞

**Comment by CarloDeSutter** [comment]
Did you change something of these?
shellrecharge.auth.pw

When I manually set the credentials in the node-red node it works.
(I normally put the credentials in the request to a node-red http node and map it like so)

![image](https://github.com/dgthomson/nodered-shellrecharge/assets/20969135/4bf844fe-d711-4273-bbbf-96bd6b76858b)

**Comment by dgthomson** [comment]
The only change is having the flow identify as a Chrome browser rather than NodeRED at one particular point in the transaction. Although I can't test starting/stopping at the moment, if I do a 'poll' then I get a result, suggesting I have managed to get an API token.

**Comment by CarloDeSutter** [comment]
Wild guess
is it possible this was unintended?

![image](https://github.com/dgthomson/nodered-shellrecharge/assets/20969135/8d8bd578-00f6-450c-87d9-213b1f7740f3)

**Comment by CarloDeSutter** [comment]
It's not a big issue, I've hardwired the password on the subflow node itself, for now.
Just that in the past I could just transmit the credential (I don't like to put it hard in the node-red flows) and then it mapped to shellrecharge.auth.pw which now it seems broken (I am guessing due to that loginPW var missing above).

Thanks for your quick and hard work

**Comment by dgthomson** [comment]
if you want to hard-wire the password then add it here inside the subflow...

<img width="413" alt="Screenshot 2024-05-02 at 10 42 13" src="https://github.com/dgthomson/nodered-shellrecharge/assets/2021563/dce0ca76-f2ce-45ad-829d-8c247f657803">

**Comment by jdeluyck** [comment]
This new version seems to do the trick!

**Comment by SupercowsNL** [comment]
After importing the 2.5 flow it start working again here :) thx!
I also had the 403 error.

**Comment by dgthomson** [comment]
Fixed and packaged version is [here](https://github.com/dgthomson/nodered-shellrecharge/blob/main/sr-2-50.json).

**Comment by DdenBraver** [comment]
I can confirm. I was running into the same issues after the firmware update on the charger.
With the 2.5 workflow all the issues are resolved.

**Comment by bigbenFE** [comment]
I had the same error with the flow, a few weeks ago after the announced update of the wallbox, the wallbox no longer loaded at all, not even with the RFID card. After Shell found the error in the new firmware, it was restored to my wallbox and informed me that I would no longer receive any updates. Since I now have the same error in the flow as everyone here, at least something new seems to have been done on the homepage ;) but thanks that it works again with 2.50 =)

**Comment by kokkie-d** [comment]
It works for me again as well.
