### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by NicoOosterwijk** [dgthomson/nodered-shellrecharge#26]
Any node to the Shell Recharge node results in token expired. Also the expire token results in this message.
Username and password are OK and working on the website of Shell-Recharge.

Please advice how to use a new token in the NR-flow.

rgds,

Nico

**Comment by BraumTown** [comment]
Previous solution by dgthomson worked for me
you could try this...

in the shell recharge node, click 'edit subflow template'
look for a section marked 'ƒ HTTP [2023-04-23]'
open the second node labelled 'Cache'
click '+ add'
into the boxes, enter
[Set] msg.requestTimeout
to the value [0-9] 10000
Done, then Deploy.

that error means that the subflow has given up waiting for shell to answer a request. this fix makes it wait longer.
