### ISSUE TITLE
403 Forbidden Error with 2.5

### ISSUE THREAD

**Issue by yoannHertienne** [dgthomson/nodered-shellrecharge#27]
Hello,

Thank you for proposing this node red subflow, very usefull.

I checked your github page one month ago, after receiving the 403 error, and I upgraded to the version 2.5 accordingly.

Everything was working fine until this week where I'm receiving following payload with version 2.5

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

![image](https://github.com/dgthomson/nodered-shellrecharge/assets/18640533/1329f137-8da6-4e8f-bf30-3a69a40053b2)

Are you aware ? any new release planned ?

**Comment by dgthomson** [comment]
Yes, there is a problem- not sure why yet. As a matter of interest, have you upgraded to Node-RED 4?

**Comment by PieDamen** [comment]
Also Having this issue since upgrade to node-red 4.

**Comment by dgthomson** [comment]
> Also Having this issue since upgrade to node-red 4.

Thanks. The subflow can't download the ``account.shellrecharge.com`` webpage which it needs to start logging in, getting a ``403: Forbidden`` error. I can run it on a Node-RED 3.1.10 installation no problem so  probably something has changed in Node-RED 4's behaviour. I'll keep looking. My guess is that it's an HTTPS issue as I get something similar on my laptop:


```
dgt@MBAir ~ % curl account.shellrecharge.com
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
dgt@MBAir ~ %
```


**Advice at the moment is not to upgrade to Node-RED 4.**

**Comment by yoannHertienne** [comment]
> Yes, there is a problem- not sure why yet. As a matter of interest, have you upgraded to Node-RED 4?

Yes, I'm using Node red 18.0.0 plugin which is implementing Node-Red V4.0.

But I cannot confirm the issue started again when node red was upgrade to V4.0 (upgrade done June 22th, so 2 days ago), but seems to be a potential reason, because it was working before

**Comment by dgthomson** [comment]
[This](https://discourse.nodered.org/t/strange-issue-with-http-request-after-upgrade-to-4-0/88892) seems to be the issue. I'll try to get a revised version out soon.

**Comment by dgthomson** [comment]
I've [uploaded a new version here ](https://github.com/dgthomson/nodered-shellrecharge/blob/main/sr-2-50-NR4FIX.json)with a possible fix if anyone's up for testing it.

**Comment by Cmbeek** [comment]
sr-2-50-NR4FIX.json worked for me. Replaced the old version of the shellrecharge node by this one and everything seems up and running correctly. Thanks a million for your Quick update!

**Comment by PieDamen** [comment]
thanks for the quick fix! Seems to be working again. However i'm getting an error: no token. 

seeing:

jQuery('#'+"login-error").html("Incorrect e-mail or password");
App.UI.show('#login-error', false, 3000);
if (document.getElementById("login-pwd")) {document.getElementById("login-pwd").value = "";};

but i'm sure the credentials are correct.

**Comment by dgthomson** [comment]
> thanks for the quick fix! Seems to be working again. However i'm getting an error: no token.
> 
> seeing:
> 
> jQuery('#'+"login-error").html("Incorrect e-mail or password"); App.UI.show('#login-error', false, 3000); if (document.getElementById("login-pwd")) {document.getElementById("login-pwd").value = "";};
> 
> but i'm sure the credentials are correct.

not sure. the fix is literally changing the phrase ``User-Agent`` to ``user-agent`` internally so if it was working for you before then I can't explain this issue, sorry.

**Comment by PieDamen** [comment]
> > thanks for the quick fix! Seems to be working again. However i'm getting an error: no token.
> > seeing:
> > jQuery('#'+"login-error").html("Incorrect e-mail or password"); App.UI.show('#login-error', false, 3000); if (document.getElementById("login-pwd")) {document.getElementById("login-pwd").value = "";};
> > but i'm sure the credentials are correct.
> 
> not sure. the fix is literally changing the phrase `User-Agent` to `user-agent` internally so if it was working for you before then I can't explain this issue, sorry.

the oddest thing.
if i put my credentials in the subflow itself, it's working :)

![image](https://github.com/dgthomson/nodered-shellrecharge/assets/63651000/442c6640-3b04-4ac3-af5f-19846c7d04af)

**Comment by yoannHertienne** [comment]
> > > thanks for the quick fix! Seems to be working again. However i'm getting an error: no token.
> > > seeing:
> > > jQuery('#'+"login-error").html("Incorrect e-mail or password"); App.UI.show('#login-error', false, 3000); if (document.getElementById("login-pwd")) {document.getElementById("login-pwd").value = "";};
> > > but i'm sure the credentials are correct.
> > 
> > 
> > not sure. the fix is literally changing the phrase `User-Agent` to `user-agent` internally so if it was working for you before then I can't explain this issue, sorry.
> 
> the oddest thing. if i put my credentials in the subflow itself, it's working :)
> 
> ![image](https://private-user-images.githubusercontent.com/63651000/342693018-442c6640-3b04-4ac3-af5f-19846c7d04af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzAxNjIsIm5iZiI6MTcxOTMyOTg2MiwicGF0aCI6Ii82MzY1MTAwMC8zNDI2OTMwMTgtNDQyYzY2NDAtM2IwNC00YWMzLWFmNWYtMTk4NDZjN2QwNGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE1Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NmRjOWJkZTFkNDFlMDQyODc1YWRjZWZjMTAzZTk2ZWE0OTE3MWJjMTllYjg3NTE0MTM0NjdiYzg3OGNmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HA-ed-QdnyhKboCtqMEH-3_-gG6sls4qwsyiVaXlo3s)

Same issue for me "Error! No token." and putting the credential in subflow works

**Comment by dgthomson** [comment]
I think this is another Node-RED 4.0.0 thing.

If I type my password into the ``Shell Recharge`` subflow instance properties box alongside my e-mail address, deploy, then have another look at the subflow instance properties box, the password has gone. So there's actually no password being sent over the internet so it fails.

Can someone else confirm this behaviour? I'll escalate to the Node-RED devs if so.

Workaround will be to add the password directly into the subflow as @PieDamen has done.

**Comment by Cmbeek** [comment]
> I think this is another Node-RED 4.0.0 thing.
> 
> If I type my password into the `Shell Recharge` subflow instance properties box alongside my e-mail address, deploy, then have another look at the subflow instance properties box, the password has gone. So there's actually no password being sent over the internet so it fails.
> 
> Can someone else confirm this behaviour? I'll escalate to the Node-RED devs if so.
> 
> Workaround will be to add the password directly into the subflow as @PieDamen has done.

I tried your sequence: Re-entered email address and password and pressed deploy. Flow kept on working (checked this by starting , stopping en polling de sub-flow) and email and password did not disappear.

Maybe this helps, maybe it doesn't (i don't have a clue about the programming): 
I did not import the complete the sr-2-50-NR4FIX.json file. During importing the file Nodered asked me if i wanted to add the file or only replace the new sub-flows. I selected the replace option.

**Comment by dgthomson** [comment]
The two issues in Node-RED 4.0.0 relevant to these bugs ([here](https://github.com/node-red/node-red/pull/4791) and [here](https://github.com/node-red/node-red/pull/4802)) have been fixed in maintenance release 4.0.1 so if you upgrade to this version the problems should go away. If you're using the sr-2-50-NR4FIX.json version of the subflow there's no particular reason to go back to the un-fixed version as it will carry on working so save yourself the bother.

**Comment by Gunterius** [comment]
wonderful !  lots of try and error for me as complete Home Assistant newbie, but i managed to start and stop the charger from the nodered flows !  Next step is to get buttons in my dashboard to do so and after that coding to do it automatically.....

Thanks !

**Comment by Gunterius** [comment]
hm, strange.  It stopped working last week.  Some analysis showed that (i have 4 inactive cards and 1 active) that before I had to enter charge token 4, now I had to suddenly change the config to 0.  It worked again.

But today again stopped working. always get HTTP error 403:start.  i tried again to load the config of charge cards (debug) and even tried all number 0 to 4.  same issue all the time.  Stopping, poll once etc works fine, just cannot start.... Anybody else has this problem now ?
