### ISSUE TITLE
Debug Forbidden

### ISSUE THREAD

**Issue by madradrakie** [dgthomson/nodered-shellrecharge#3]
Hello,

Yesterday the flow was working, today i get the following error when i try to start the charging session:

error : msg : Object
object
_msgid: "de254ceb2f2e36f6"
payload: "Failed action 'start'"
error: object
message: "Forbidden"
topic: "error"

When i do the info command i get the following information:

12-1-2023 06:36:21[node: Debug](http://192.168.2.92:1880/#)
error : msg : Object
object
_msgid: "795f89a3e76bcc12"
payload: "Failed action 'info'"
error: object
topic: "error"

12-1-2023 06:36:26[node: Debug](http://192.168.2.92:1880/#)
response : msg : Object
object
_msgid: "795f89a3e76bcc12"
payload: object
assets: object
chargePoints: array[1]
chargeTokens: array[3]
0: object
1: object
2: object
topic: "response"

Have i done something wrong? Yesterday it was working.

Thanks in advance

**Comment by Marc1200** [comment]
I have the same problem, i also get the message forbidden at the all the commands. 
i entered the timestamps at the commands 
Do you have solution @dgthomson ?

**Comment by dgthomson** [comment]
Duplicate
