### ISSUE TITLE
Info gives errors

### ISSUE THREAD

**Issue by tnagels** [dgthomson/nodered-shellrecharge#4]
When I perform the "info action" I get following error:
```
node: HTTP parameters
msg : string[97]
"Invalid JSONata expression: Argument 3 of function "fromMillis" does not match function signature"
```

**Comment by tnagels** [comment]
My bad. I read over the part where it states you have to add the times to the input trigger. Bit confusing that they were not in the flow you can download from github though.

**Comment by Marc1200** [comment]
Where should i add times  to the input trigger?
