### ISSUE TITLE
Energy action gives errors

### ISSUE THREAD

**Issue by tnagels** [dgthomson/nodered-shellrecharge#5]
When I perform the energy action I get following errors: 

```
node: b1dadd50f18e19f2
msg : string[50]
"Cannot set property of non-object type: dates.from"
node: b1dadd50f18e19f2
msg : string[48]
"Cannot set property of non-object type: dates.to"
```

**Comment by tnagels** [comment]
My bad. Did not provide the times which are needed. It is mentioned in the readme, but it is confusing that they are missing in the downloadable flow.

**Comment by Marc1200** [comment]
How did you add times tot the input?

![image](https://user-images.githubusercontent.com/68737063/220466267-054226b9-f50b-4021-8207-ef3c10a4da4c.png)

there was an error on this function
