### ISSUE TITLE
info outputs error

### ISSUE THREAD

**Issue by Marc1200** [dgthomson/nodered-shellrecharge#6]
Hello,
Info command outputs this:
![image](https://user-images.githubusercontent.com/68737063/221354082-d5ee4585-dc64-47cd-901f-1a6263e2fbbd.png)

i have entered the authentication correctly, the energy command does work correctly.

**Comment by edautz** [comment]
Maybe the same problem, but since last week info doesn’t work anymore.

Nodered debug output:

TypeError: Cannot read properties of undefined (reading 'energy')

**Comment by dgthomson** [comment]
Thanks, I can see "The supplied authentication is invalid" message too. The flow keeps running though and the chargePoints/chargeTokens data is sent from Shell Recharge even with this error. Unfortunately I don't have much time at the moment to fiddle but I'll have a deeper look when I can.

**Comment by dgthomson** [comment]
OK so the error is coming from a part of the flow involved in retrieving energy consumption data. The process is all undocumented and the inspiration originally came from Github code written by [Siumba](https://github.com/Siumba/NewMotionAPI). This now needs more detailed authentication to access.

This flow is a hack and effectively fakes an interaction between Node-RED and the Shell Recharge website to work. Until Shell gives access to their [API](https://developer.shell.com/api-catalog) to individuals this issue can't be fixed.

{ 'action' : 'info' } will work to get chargePoints/chargeTokens but not energy data.

{ 'action' : 'energy' } has never been reliable.

**Comment by Marc1200** [comment]
Okay, 
Info and energy are not so important for me.
But the most important part of the integration for me is to start, stop the charging station but with that i got this error:
![9d1c491f862db027018d4c3c19f87a4319f76995](https://user-images.githubusercontent.com/68737063/221404811-cd4baf56-72ea-4698-b2ed-3ea8e813e92e.png)

I created a new issue of this problem
