### ISSUE TITLE
Actions start, stop outputs error not found or not permitted

### ISSUE THREAD

**Issue by Marc1200** [dgthomson/nodered-shellrecharge#7]
I have a problem with the action start stop, when i inject start and stop then i get the following error:
![9d1c491f862db027018d4c3c19f87a4319f76995](https://user-images.githubusercontent.com/68737063/221405488-10f3e01c-3931-40d8-8620-7cb1eef75980.png)
@dgthomson do you know what the problem is?
Or is this also because of changing shell api?

**Comment by dgthomson** [comment]
Not sure. I have uploaded a version for you. Please send over as much of its debug output as possible.

**Comment by Marc1200** [comment]
Below are the screenshots of the debug output, i saw a double slash between chargepoints and remote-control maybe that is something wrong
![image](https://user-images.githubusercontent.com/68737063/221406127-6b7fc3c9-0583-4a4b-8344-8f6b1ad95d85.png)
![image](https://user-images.githubusercontent.com/68737063/221406167-6eb60735-60d2-46c6-a796-1afdeb6e2456.png)
![image](https://user-images.githubusercontent.com/68737063/221406187-7f883f1c-5ae5-4327-be5f-429608a05c80.png)
![image](https://user-images.githubusercontent.com/68737063/221406197-7ddd9181-10da-475f-8abe-863cc9724c92.png)

**Comment by dgthomson** [comment]
> Below are the screenshots of the debug output, i saw a double slash between chargepoints and remote-control

Yes, that's a problem [the charger UUID should be there]. In the node setup, what have you entered in Charger ID and Card ID?

<img width="493" alt="Screenshot 2023-02-26 at 11 15 27" src="https://user-images.githubusercontent.com/2021563/221407276-144cb843-25f6-4544-87fb-366bc84bc4e3.png">

**Comment by Marc1200** [comment]
I entered the entire array of chargepoints into charger id
And the chargetokens array into card id

**Comment by dgthomson** [comment]
Enter just a number corresponding with the array index...

<img width="438" alt="Data" src="https://user-images.githubusercontent.com/2021563/221408099-7750159f-eb57-4374-ad6a-9e6deecd40b1.png">

**Comment by Marc1200** [comment]
Okay, when i use 2 cards, can i add a payload to the start command to choose the card which i'm using for charge ?

**Comment by dgthomson** [comment]
There is a version [Marc1200-cardid.json](https://github.com/dgthomson/nodered-shellrecharge/blob/main/Marc1200-cardid.json) that you can try. It accepts

msg.payload.cardid: _\<number\>_

to select whichever card you want for the session.

_(Edited)_

**Comment by Marc1200** [comment]
Okay,
I will try later with 2 cards, i know configured it with one card. 
Start, stop and charging status are working perfectly.
Many thanks for the help!
